const fs = require('fs');
const path = require('path');

const en = JSON.parse(fs.readFileSync(path.join(__dirname, '../messages/en.json'), 'utf8'));

// High quality Spanish translation mappings for CRM Template for WhatsApp
const es = {
  LoginPage: {
    titleAccept: "Aceptar invitación",
    titleWelcome: "Bienvenido de nuevo",
    descAccept: "Inicia sesión en tu cuenta para unirte a {accountName}",
    descWelcome: "Ingresa tus credenciales para acceder a tu CRM de WhatsApp",
    emailLabel: "Correo electrónico",
    emailPlaceholder: "nombre@empresa.com",
    passwordLabel: "Contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    passwordPlaceholder: "••••••••",
    signingIn: "Iniciando sesión...",
    signIn: "Iniciar sesión",
    noAccount: "¿No tienes una cuenta?",
    createAccount: "Crear una cuenta"
  },
  Sidebar: {
    title: "WA CRM WhatsApp",
    dashboard: "Panel Principal",
    inbox: "Bandeja de Entrada",
    notifications: "Notificaciones",
    contacts: "Contactos",
    pipelines: "Embudo de Ventas",
    broadcasts: "Campañas Masivas",
    automations: "Automatizaciones",
    flows: "Flujos",
    aiAgents: "Agentes IA",
    saasClients: "Clientes SaaS",
    settings: "Configuración",
    beta: "Beta",
    unreadConversations: "{count} {count, plural, =1 {conversación no leída} other {conversaciones no leídas}}",
    unreadNotifications: "{count} {count, plural, =1 {notificación no leída} other {notificaciones no leídas}}",
    roleOwner: "Propietario",
    roleAdmin: "Administrador",
    roleAgent: "Agente",
    roleViewer: "Observador",
    closeMenu: "Cerrar menú",
    defaultUser: "Usuario",
    defaultAvatar: "Avatar",
    menuProfile: "Mi Perfil",
    menuSettings: "Configuración",
    menuSignOut: "Cerrar sesión"
  },
  Header: {
    dashboard: "Panel Principal",
    inbox: "Bandeja de Entrada",
    notifications: "Notificaciones",
    contacts: "Contactos",
    pipelines: "Embudo de Ventas",
    broadcasts: "Campañas Masivas",
    automations: "Automatizaciones",
    settings: "Configuración",
    openMenu: "Abrir menú",
    openAccountMenu: "Abrir menú de cuenta",
    defaultUser: "Usuario",
    defaultAvatar: "Avatar",
    menuProfile: "Mi Perfil",
    menuSettings: "Configuración",
    menuSignOut: "Cerrar sesión"
  },
  ModeToggle: {
    switchMode: "Cambiar modo de tema"
  },
  AccountAccess: {
    unlinkedTitle: "Cuenta no vinculada",
    unlinkedBody: "Tu usuario no está vinculado a ninguna empresa activa. Contacta al administrador.",
    errorTitle: "Error al cargar la cuenta",
    errorBody: "No pudimos resolver la información de tu cuenta. Por favor intenta de nuevo.",
    retry: "Reintentar"
  },
  Dashboard: {
    page: {
      title: "Panel Principal",
      subtitle: "Resumen de rendimiento de tu WhatsApp CRM",
      activeConversations: "Conversaciones Activas",
      messagesToday: "Mensajes Hoy",
      dealsWon: "Ventas Ganadas",
      conversionRate: "Tasa de Conversión",
      trendUp: "+{pct}% vs semana anterior",
      trendDown: "-{pct}% vs semana anterior",
      loading: "Cargando métricas...",
      error: "Error al cargar datos del panel"
    },
    quickActions: {
      title: "Acciones Rápidas",
      newBroadcast: "Nueva Campaña",
      addContact: "Nuevo Contacto",
      viewInbox: "Ir a Bandeja de Entrada"
    },
    activityFeed: {
      title: "Actividad Reciente",
      empty: "No hay actividad reciente para mostrar.",
      messageSent: "Mensaje enviado a {name}",
      messageReceived: "Mensaje recibido de {name}",
      dealMoved: "Trato movido a {stage}",
      contactCreated: "Contacto {name} creado",
      broadcastCompleted: "Campaña {name} completada",
      viewAll: "Ver todo",
      loading: "Cargando actividad...",
      filterAll: "Todo"
    },
    conversationsChart: {
      title: "Volumen de Conversaciones",
      subtitle: "Interacciones diarias con clientes en los últimos 30 días",
      tooltipLabel: "{count} conversaciones",
      inbound: "Mensajes Entrantes",
      outbound: "Mensajes Salientes",
      today: "Hoy",
      thisWeek: "Esta Semana",
      thisMonth: "Este Mes",
      empty: "Sin datos de conversaciones aún",
      loading: "Cargando gráfico..."
    },
    pipelineDonut: {
      title: "Distribución del Embudo",
      subtitle: "Valor total y tratos activos por etapa",
      totalDeals: "{count} tratos",
      totalValue: "Valor total: {value}",
      empty: "Sin tratos en el embudo",
      loading: "Cargando embudo...",
      stageLabel: "{stage}: {count} ({value})"
    },
    responseTimeChart: {
      title: "Tiempo Medio de Respuesta",
      subtitle: "Velocidad de respuesta de tus agentes a clientes",
      avgMinutes: "{min} min",
      faster: "{pct}% más rápido que el promedio",
      slower: "{pct}% más lento que el promedio",
      empty: "Sin datos de tiempo de respuesta",
      loading: "Cargando tiempos..."
    },
    emptyState: {
      desc: "Conecta tu número de WhatsApp en Configuración para comenzar a recibir mensajes y ver métricas en tiempo real."
    }
  },
  Inbox: {
    page: {
      title: "Bandeja de Entrada"
    },
    conversationList: {
      searchPlaceholder: "Buscar por nombre, número o mensaje...",
      filterAll: "Todos",
      filterUnread: "No leídos",
      filterAssignedToMe: "Mis asignados",
      filterUnassigned: "Sin asignar",
      filterOpen: "Abiertos",
      filterClosed: "Cerrados",
      emptyTitle: "Sin conversaciones",
      emptyDesc: "Los mensajes nuevos de WhatsApp aparecerán aquí automáticamente.",
      loading: "Cargando conversaciones...",
      noResults: "No se encontraron conversaciones con ese filtro.",
      activeSessionBadge: "Sesión 24h activa",
      sessionExpiredBadge: "Sesión 24h expirada"
    },
    messageThread: {
      selectConversation: "Selecciona una conversación para ver los mensajes",
      typeMessage: "Escribe un mensaje...",
      send: "Enviar",
      audioNote: "Nota de voz",
      image: "Imagen",
      document: "Documento",
      video: "Video",
      pagoMovilCapture: "Capture Pago Móvil",
      contactDetails: "Detalles del Contacto",
      closeConversation: "Cerrar Conversación",
      reopenConversation: "Reabrir Conversación",
      assignTo: "Asignar a...",
      assignMe: "Asignarme a mí",
      assignedSuccess: "Conversación asignada",
      closedSuccess: "Conversación cerrada",
      reopenedSuccess: "Conversación reabierta",
      sending: "Enviando...",
      delivered: "Entregado",
      read: "Leído",
      failed: "Error de envío",
      retry: "Reintentar"
    },
    sessionTimer: {
      windowActive: "Ventana de sesión 24h abierta (Mensajes ilimitados)",
      windowRemaining: "Quedan {time} de sesión gratuita",
      windowExpired: "Ventana de 24h cerrada. El próximo mensaje abrirá una nueva sesión.",
      tip: "Modelo oficial de conversación de 24 horas"
    },
    composer: {
      placeholder: "Escribe un mensaje a {name}... (Shift + Enter para salto de línea)",
      attachFile: "Adjuntar archivo o imagen",
      attachMedia: "Foto o Video",
      attachDoc: "Documento PDF",
      quickReply: "Respuesta Rápida (/)",
      useAiDraft: "Redactar con IA",
      recordingAudio: "Grabando nota de voz...",
      cancelAudio: "Cancelar",
      sendAudio: "Enviar audio",
      template: "Plantilla Oficial",
      dropFilesHere: "Arrastra tus archivos aquí para enviarlos",
      fileTooLarge: "El archivo excede el tamaño máximo permitido",
      emptyMessage: "Escribe un mensaje antes de enviar",
      variables: "Insertar variable",
      variableName: "Nombre del contacto",
      variablePhone: "Teléfono",
      aiGenerating: "La IA está redactando la respuesta...",
      aiDraftReady: "Borrador de IA generado",
      applyDraft: "Aplicar al editor",
      discardDraft: "Descartar",
      errorSending: "Error al enviar mensaje",
      sentSuccess: "Mensaje enviado",
      charCount: "{count} caracteres",
      bold: "Negrita (*texto*)",
      italic: "Cursiva (_texto_)",
      strikethrough: "Tachado (~texto~)"
    },
    bubble: {
      you: "Tú",
      bot: "Agente IA",
      agent: "Agente",
      customer: "Cliente",
      deliveredAt: "Entregado {time}",
      readAt: "Leído {time}",
      download: "Descargar archivo",
      playAudio: "Reproducir audio",
      pauseAudio: "Pausar audio",
      viewFullImage: "Ver imagen completa",
      ocrVerified: "OCR Pago Móvil Verificado",
      bankRef: "Ref: {ref}",
      bankAmount: "Monto: {amount}",
      bankOrigin: "Banco: {bank}",
      copyText: "Copiar texto",
      copied: "Copiado al portapapeles"
    },
    mediaViewer: {
      title: "Visualizador de Archivo",
      download: "Descargar",
      close: "Cerrar",
      zoomIn: "Acercar",
      zoomOut: "Alejar",
      rotate: "Rotar",
      page: "Página {current} de {total}",
      next: "Siguiente",
      prev: "Anterior",
      loading: "Cargando archivo...",
      error: "No se pudo cargar el archivo multimedia"
    },
    actions: {
      markAsRead: "Marcar como leído",
      markAsUnread: "Marcar como no leído",
      muteNotifications: "Silenciar notificaciones",
      deleteConversation: "Eliminar conversación",
      exportChat: "Exportar chat",
      createDeal: "Crear trato en embudo",
      addTag: "Agregar etiqueta",
      removeTag: "Quitar etiqueta"
    },
    replyQuote: {
      replyingTo: "Respondiendo a {name}",
      cancel: "Cancelar respuesta",
      originalMessage: "Mensaje original: {text}",
      photo: "Foto",
      voice: "Nota de voz",
      video: "Video",
      document: "Documento",
      unsupported: "Archivo adjunto",
      quotedDeleted: "Mensaje citado no disponible"
    },
    templatePicker: {
      title: "Seleccionar Plantilla de WhatsApp",
      search: "Buscar plantillas aprobadas...",
      noTemplates: "No tienes plantillas creadas o aprobadas en WhatsApp.",
      createOne: "Crear plantilla en Configuración",
      preview: "Vista previa",
      header: "Encabezado",
      body: "Cuerpo del mensaje",
      footer: "Pie de página",
      buttons: "Botones",
      useTemplate: "Usar plantilla",
      cancel: "Cancelar",
      missingVariables: "Por favor completa las variables requeridas",
      variablePlaceholder: "Valor para {name}"
    },
    sidebar: {
      contactInfo: "Información del Cliente",
      phone: "Teléfono WhatsApp",
      email: "Correo Electrónico",
      assignedTo: "Agente Asignado",
      tags: "Etiquetas",
      addTagPlaceholder: "+ Agregar etiqueta...",
      notes: "Notas internas del contacto"
    },
    aiBanner: {
      title: "Asistente IA Activo",
      subtitle: "El bot responderá automáticamente a las consultas de este cliente usando Gemini y tus catálogos.",
      pauseAi: "Pausar IA en este chat",
      resumeAi: "Reactivar IA en este chat",
      pausedNotice: "La IA está pausada para esta conversación. Un agente humano debe responder.",
      resumedNotice: "La IA ha sido reactivada para esta conversación.",
      tokensUsed: "{count} tokens consumidos",
      handoffNotice: "El bot transfirió la conversación porque el cliente solicitó un humano."
    }
  },
  Contacts: {
    page: {
      title: "Contactos",
      subtitle: "Gestiona tu base de datos de clientes de WhatsApp",
      newContact: "Nuevo Contacto",
      importContacts: "Importar CSV",
      exportContacts: "Exportar",
      searchPlaceholder: "Buscar por nombre, teléfono, correo o empresa...",
      allContacts: "Todos los contactos ({count})",
      filterByTag: "Filtrar por etiqueta",
      noContacts: "No hay contactos registrados.",
      noContactsDesc: "Los contactos se crearán automáticamente cuando te escriban por WhatsApp o puedes añadirlos manualmente.",
      createFirstContact: "Crear primer contacto",
      nameCol: "Nombre",
      phoneCol: "Teléfono",
      emailCol: "Correo",
      tagsCol: "Etiquetas",
      createdCol: "Fecha de registro",
      actionsCol: "Acciones",
      edit: "Editar",
      delete: "Eliminar",
      deleteConfirm: "¿Eliminar contacto?",
      deleteConfirmDesc: "Esta acción no se puede deshacer. Se conservará el historial de mensajes pero el contacto será removido.",
      cancel: "Cancelar",
      deleting: "Eliminando...",
      deletedSuccess: "Contacto eliminado",
      editSuccess: "Contacto actualizado",
      createSuccess: "Contacto creado con éxito",
      loadFailed: "Error al cargar contactos",
      selectedCount: "{count} seleccionados",
      bulkDelete: "Eliminar seleccionados",
      bulkTag: "Asignar etiquetas",
      phoneInvalid: "Ingresa un número telefónico en formato internacional (Ej: +584121234567)"
    },
    form: {
      titleNew: "Crear Contacto",
      titleEdit: "Editar Contacto",
      nameLabel: "Nombre Completo *",
      namePlaceholder: "Ej: María Rodríguez",
      phoneLabel: "Número de Teléfono / WhatsApp *",
      phonePlaceholder: "+58 412 1234567",
      phoneHint: "Debe incluir el código de país (Ej: +58 para Venezuela, +57 para Colombia)",
      emailLabel: "Correo Electrónico",
      emailPlaceholder: "maria@ejemplo.com",
      companyLabel: "Empresa",
      companyPlaceholder: "Ej: Distribuidora Sol C.A.",
      tagsLabel: "Etiquetas",
      tagsPlaceholder: "Seleccionar o crear etiquetas...",
      notesLabel: "Notas Internas",
      notesPlaceholder: "Anotaciones sobre preferencias, compras anteriores o requerimientos...",
      cancel: "Cancelar",
      save: "Guardar Contacto",
      saving: "Guardando...",
      nameRequired: "El nombre es obligatorio",
      phoneRequired: "El número de teléfono es obligatorio",
      customFieldsSection: "Campos Personalizados",
      noCustomFields: "No hay campos personalizados configurados.",
      createFieldHint: "Puedes crear campos personalizados en Configuración > Campos.",
      avatarLabel: "Foto de perfil",
      changeAvatar: "Cambiar foto",
      removeAvatar: "Quitar foto",
      addressLabel: "Dirección",
      addressPlaceholder: "Calle, Ciudad, Estado",
      cityLabel: "Ciudad",
      cityPlaceholder: "Caracas",
      countryLabel: "País",
      countryPlaceholder: "Venezuela"
    },
    detailView: {
      overview: "Resumen",
      conversations: "Historial de Conversaciones",
      deals: "Tratos del Cliente",
      activity: "Historial de Actividad",
      sendMessage: "Enviar Mensaje de WhatsApp",
      openInInbox: "Abrir en Bandeja de Entrada",
      noDeals: "Este contacto no tiene tratos en el embudo.",
      createDeal: "Crear Nuevo Trato",
      totalSpent: "Total Comprado",
      lastContacted: "Último Contacto: {date}",
      neverContacted: "Nunca contactado",
      leadScore: "Puntuación de Prospecto",
      status: "Estado del Contacto",
      statusActive: "Cliente Activo",
      statusLead: "Prospecto",
      statusInactive: "Inactivo",
      contactInfoTitle: "Datos de Contacto",
      detailsTitle: "Propiedades",
      createdDate: "Registrado el {date}",
      updatedDate: "Actualizado el {date}",
      assignedAgent: "Agente Asignado",
      unassigned: "Sin Asignar",
      dealsCount: "{count} tratos asociados",
      notesCount: "{count} notas",
      addNote: "Agregar nota rápida...",
      saveNote: "Guardar nota",
      noteSaved: "Nota guardada con éxito",
      deleteNote: "Eliminar nota",
      confirmDeleteNote: "¿Eliminar esta nota?",
      notesEmpty: "No hay notas para este contacto."
    },
    importModal: {
      title: "Importar Contactos desde CSV",
      description: "Sube un archivo .csv con los números de teléfono y nombres de tus clientes.",
      step1: "1. Seleccionar Archivo",
      step2: "2. Mapear Columnas",
      step3: "3. Importar",
      chooseFile: "Seleccionar archivo CSV",
      dragDrop: "o arrastra el archivo aquí",
      downloadTemplate: "Descargar plantilla de ejemplo CSV",
      mapName: "Columna de Nombre",
      mapPhone: "Columna de Teléfono (Obligatoria)",
      mapEmail: "Columna de Correo",
      mapCompany: "Columna de Empresa",
      mapTags: "Columna de Etiquetas",
      previewRows: "Vista previa de las primeras {count} filas",
      startImport: "Comenzar Importación",
      importing: "Importando contactos...",
      successTitle: "¡Importación completada con éxito!",
      successSummary: "Se importaron {imported} contactos correctamente. ({duplicates} duplicados ignorados, {errors} errores).",
      cancel: "Cancelar",
      close: "Cerrar",
      invalidCsv: "El archivo no es un CSV válido o está vacío",
      requiredColumnsMissing: "Debes mapear al menos la columna de Teléfono",
      tagsNotice: "Las etiquetas separadas por comas se asignarán automáticamente a cada contacto.",
      overwriteDuplicates: "Actualizar datos si el contacto ya existe",
      skipDuplicates: "Ignorar contactos duplicados (Recomendado)",
      errorListTitle: "Filas con errores:",
      lineError: "Fila {row}: {error}",
      tryAgain: "Intentar con otro archivo",
      back: "Atrás",
      next: "Siguiente"
    },
    customFields: {
      title: "Campos Personalizados",
      desc: "Define atributos propios de tu negocio para almacenar en cada contacto (Ej: Cédula/RIF, Dirección de Envío, Talla).",
      addField: "Nuevo Campo",
      fieldName: "Nombre del Campo",
      fieldType: "Tipo de Dato",
      typeText: "Texto Corto",
      typeNumber: "Número",
      typeDate: "Fecha",
      typeSelect: "Lista de Opciones",
      typeBoolean: "Casilla (Sí/No)",
      save: "Guardar Campo",
      saving: "Guardando...",
      delete: "Eliminar Campo",
      confirmDelete: "¿Seguro que deseas eliminar este campo?",
      empty: "No has configurado campos personalizados.",
      savedSuccess: "Campo guardado con éxito",
      deletedSuccess: "Campo eliminado con éxito"
    }
  },
  Pipelines: {
    page: {
      title: "Embudo de Ventas (CRM)",
      subtitle: "Gestiona las oportunidades comerciales y prospectos en cada etapa de venta",
      newDeal: "Nuevo Trato",
      settings: "Gestionar Etapas",
      analytics: "Estadísticas del Embudo",
      totalPipelineValue: "Valor Total: {value}",
      dealsCount: "{count} tratos activos",
      searchPlaceholder: "Buscar trato por nombre, contacto o monto...",
      allPipelines: "Embudo Principal",
      loading: "Cargando embudo...",
      emptyPipeline: "No hay tratos en este embudo.",
      createFirstDeal: "Crear tu primer trato",
      wonStage: "Ganado",
      lostStage: "Perdido",
      moveDeal: "Mover a otra etapa",
      filterAgent: "Filtrar por agente",
      filterAll: "Todos los agentes",
      dragDropHint: "Arrastra y suelta las tarjetas para avanzar de etapa"
    },
    board: {
      stageDealsCount: "{count} tratos",
      stageTotalValue: "{value}"
    },
    card: {
      contact: "Contacto: {name}",
      value: "Monto: {value}",
      daysInStage: "{days}d en esta etapa"
    },
    form: {
      titleNew: "Crear Nuevo Trato",
      titleEdit: "Editar Trato",
      titleLabel: "Título del Trato *",
      titlePlaceholder: "Ej: Venta de Repuestos - Taller Central",
      contactLabel: "Contacto Asociado *",
      contactPlaceholder: "Buscar contacto...",
      valueLabel: "Valor Estimado ($ USD) *",
      valuePlaceholder: "0.00",
      stageLabel: "Etapa Inicial *",
      pipelineLabel: "Embudo",
      expectedCloseLabel: "Fecha Estimada de Cierre",
      assignedToLabel: "Agente Responsable",
      notesLabel: "Detalles u Observaciones del Negocio",
      notesPlaceholder: "Productos cotizados, condiciones acordadas...",
      cancel: "Cancelar",
      save: "Guardar Trato",
      saving: "Guardando...",
      titleRequired: "El título es obligatorio",
      contactRequired: "Debes seleccionar un contacto",
      valueRequired: "El monto es obligatorio",
      deleteDeal: "Eliminar Trato",
      confirmDelete: "¿Seguro que deseas eliminar este trato?",
      deleteSuccess: "Trato eliminado",
      saveSuccess: "Trato guardado exitosamente",
      markWon: "Marcar como Ganado",
      markLost: "Marcar como Perdido",
      reopen: "Reabrir Trato",
      wonReason: "Motivo de Ganancia (Opcional)",
      lostReason: "Motivo de Pérdida *",
      lostReasonPlaceholder: "Ej: Precio muy alto, eligió a competidor...",
      lostReasonRequired: "Debes indicar el motivo de la pérdida",
      createdSuccess: "Trato creado exitosamente",
      currency: "Moneda",
      priorityLabel: "Prioridad",
      priorityLow: "Baja",
      priorityMedium: "Media",
      priorityHigh: "Alta (Urgente)"
    },
    settings: {
      title: "Configuración de Etapas del Embudo",
      description: "Personaliza las etapas de tu ciclo de ventas para adaptarlas al flujo de tu negocio.",
      addStage: "Nueva Etapa",
      stageName: "Nombre de la Etapa",
      stageColor: "Color identificador",
      winProbability: "Probabilidad de Éxito (%)",
      deleteStage: "Eliminar Etapa",
      confirmDeleteStage: "¿Eliminar esta etapa? Los tratos activos deberán ser reubicados.",
      saveStages: "Guardar Cambios",
      saving: "Guardando etapas...",
      saveSuccess: "Etapas actualizadas con éxito",
      defaultStageLead: "Prospecto / Nuevo Lead",
      defaultStageContacted: "Contactado / Conversación",
      defaultStageProposal: "Propuesta Enviada / Cotización",
      defaultStageNegotiation: "En Negociación",
      defaultStageWon: "Cerrado Ganado",
      defaultStageLost: "Cerrado Perdido",
      cannotDeleteOnlyStage: "Debe haber al menos una etapa activa",
      dragToReorder: "Arrastra para ordenar las etapas"
    },
    analytics: {
      title: "Rendimiento del Embudo",
      subtitle: "Conversión y velocidad de cierre de ventas",
      winRate: "Tasa de Éxito",
      avgDealSize: "Ticket Promedio",
      timeToClose: "Ciclo Promedio de Venta",
      totalWonValue: "Monto Total Ganado",
      totalLostValue: "Monto Total Perdido",
      dealsByStage: "Tratos por Etapa",
      conversionFunnel: "Embudo de Conversión",
      loading: "Cargando analíticas...",
      daysAvg: "{days} días",
      emptyAnalytics: "Se necesitan más tratos cerrados para generar estadísticas completas."
    }
  },
  Broadcasts: {
    page: {
      title: "Campañas Masivas de WhatsApp",
      subtitle: "Envía mensajes masivos y notificaciones a listas de clientes segmentadas",
      newBroadcast: "Nueva Campaña",
      allCampaigns: "Historial de Campañas ({count})",
      loading: "Cargando campañas...",
      empty: "No has creado ninguna campaña masiva aún.",
      createFirst: "Crear tu primera campaña",
      nameCol: "Nombre de Campaña"
    },
    status: {
      draft: "Borrador",
      scheduled: "Programada",
      running: "Enviando...",
      paused: "Pausada",
      completed: "Completada",
      failed: "Error",
      cancelled: "Cancelada",
      stats: "{sent} enviados / {failed} fallidos / {total} total",
      progress: "{pct}% completado",
      deliveredCount: "{count} entregados"
    },
    detail: {
      title: "Detalle de Campaña: {name}",
      overview: "Resumen de Rendimiento",
      recipients: "Destinatarios ({count})",
      templateUsed: "Plantilla Utilizada",
      scheduledFor: "Programada para: {date}",
      completedAt: "Finalizada el: {date}",
      sentCount: "Mensajes Enviados",
      deliveredCount: "Entregados",
      readCount: "Leídos",
      failedCount: "Fallidos",
      deliveryRate: "Tasa de Entrega",
      readRate: "Tasa de Lectura",
      pauseCampaign: "Pausar Campaña",
      resumeCampaign: "Reanudar Campaña",
      cancelCampaign: "Cancelar Campaña",
      duplicateCampaign: "Duplicar Campaña",
      deleteCampaign: "Eliminar Campaña",
      confirmDelete: "¿Seguro que deseas eliminar esta campaña?",
      deletedSuccess: "Campaña eliminada",
      pausedSuccess: "Campaña pausada",
      resumedSuccess: "Campaña reanudada",
      cancelledSuccess: "Campaña cancelada",
      retryFailed: "Reintentar mensajes fallidos",
      retrying: "Reintentando envíos...",
      recipientPhone: "Teléfono",
      recipientStatus: "Estado de Envío",
      recipientError: "Detalle de Error",
      exportResults: "Descargar Reporte en CSV",
      loading: "Cargando detalles...",
      back: "Volver a Campañas"
    },
    new: {
      title: "Crear Nueva Campaña de WhatsApp",
      step1: "1. Información General",
      step2: "2. Seleccionar Audiencia",
      step3: "3. Elegir Plantilla / Mensaje",
      step4: "4. Programación y Confirmación",
      cancel: "Cancelar",
      next: "Continuar",
      back: "Atrás"
    },
    wizard: {
      campaignName: "Nombre de la Campaña *",
      campaignNamePlaceholder: "Ej: Promoción Día de las Madres 2026",
      selectAudience: "Segmento de Clientes Destinatarios *",
      allContacts: "Todos los contactos con WhatsApp",
      filterByTags: "Filtrar por etiquetas específicas",
      totalRecipients: "Total de destinatarios calculados: {count}",
      selectTemplate: "Plantilla de WhatsApp Aprobada *",
      scheduleNow: "Enviar inmediatamente al confirmar",
      scheduleLater: "Programar para fecha y hora específica",
      launchCampaign: "Lanzar Campaña",
      scheduling: "Programando campaña..."
    }
  },
  Automations: {
    list: {
      title: "Automatizaciones",
      subtitle: "Reglas automáticas basadas en eventos (nuevos mensajes, cambios de estado, etiquetas)",
      newRule: "Nueva Automatización",
      empty: "No tienes automatizaciones configuradas.",
      createFirst: "Crear primera regla",
      ruleName: "Nombre de la Regla",
      trigger: "Disparador (Cuándo)",
      action: "Acción (Entonces)",
      status: "Estado",
      active: "Activa",
      inactive: "Inactiva",
      toggleActive: "Activar / Pausar",
      delete: "Eliminar",
      confirmDelete: "¿Eliminar esta automatización?",
      edit: "Editar",
      logs: "Ver Registro de Ejecuciones",
      runsCount: "{count} ejecuciones",
      loading: "Cargando reglas...",
      createdSuccess: "Regla creada exitosamente",
      updatedSuccess: "Regla actualizada",
      deletedSuccess: "Regla eliminada"
    },
    edit: {
      titleNew: "Crear Automatización",
      titleEdit: "Editar Automatización",
      save: "Guardar Automatización"
    },
    logs: {
      title: "Historial de Ejecuciones de Automatización",
      subtitle: "Registro en tiempo real de reglas disparadas y acciones ejecutadas",
      time: "Fecha / Hora",
      rule: "Regla",
      contact: "Contacto",
      status: "Resultado",
      success: "Completado con Éxito",
      failed: "Error en Ejecución",
      details: "Detalles",
      noLogs: "No hay registros de ejecución aún.",
      clearLogs: "Limpiar registros"
    },
    builder: {
      nameLabel: "Nombre de la Regla *",
      namePlaceholder: "Ej: Asignar agente cuando prospecto responde",
      triggerSection: "1. ¿Cuándo se debe activar esta regla? (Disparador)",
      triggerNewMessage: "Cuando entra un nuevo mensaje de WhatsApp",
      triggerTagAdded: "Cuando se añade una etiqueta a un contacto",
      triggerDealMoved: "Cuando un trato se mueve a otra etapa",
      triggerContactCreated: "Cuando se registra un nuevo contacto",
      actionSection: "2. ¿Qué acción debe realizar el sistema? (Acción)",
      actionSendWhatsApp: "Enviar mensaje o plantilla de WhatsApp",
      actionAddTag: "Agregar etiqueta al contacto",
      actionRemoveTag: "Remover etiqueta del contacto",
      actionAssignAgent: "Asignar a un agente del equipo",
      actionCreateDeal: "Crear automáticamente un trato en el embudo",
      actionNotifyTeam: "Enviar notificación interna al equipo",
      actionWebhook: "Disparar Webhook externo (HTTP POST)",
      conditionsSection: "Condiciones Adicionales (Opcional)",
      addCondition: "+ Agregar Condición",
      cancel: "Cancelar",
      save: "Guardar Regla",
      saving: "Guardando...",
      selectTriggerPlaceholder: "Selecciona el evento disparador",
      selectActionPlaceholder: "Selecciona la acción a ejecutar",
      messageTextPlaceholder: "Escribe el texto del mensaje a enviar...",
      selectTagPlaceholder: "Seleccionar etiqueta",
      selectAgentPlaceholder: "Seleccionar agente",
      selectStagePlaceholder: "Seleccionar etapa del embudo"
    }
  },
  Flows: {
    list: {
      title: "Flujos de Conversación (Chatbots)",
      subtitle: "Diseña flujos visuales interactivos con menús, botones y respuestas automatizadas",
      newFlow: "Nuevo Flujo",
      empty: "No tienes flujos de conversación creados.",
      createFirst: "Crear tu primer flujo visual",
      flowName: "Nombre del Flujo",
      triggerKeyword: "Palabra Clave Disparadora",
      nodesCount: "{count} bloques",
      runsCount: "{count} sesiones",
      status: "Estado",
      active: "Activo en WhatsApp",
      inactive: "En Borrador",
      edit: "Abrir Editor Visual",
      delete: "Eliminar Flujo",
      confirmDelete: "¿Seguro que deseas eliminar este flujo?",
      loading: "Cargando flujos...",
      createdSuccess: "Flujo creado con éxito",
      deletedSuccess: "Flujo eliminado",
      toggleActive: "Publicar / Pausar",
      duplicate: "Duplicar Flujo",
      templates: "Plantillas de Flujos Predefinidas",
      useTemplate: "Usar Plantilla",
      templateFaq: "Menú Principal y Preguntas Frecuentes",
      templateLead: "Captura y Calificación de Prospectos",
      templateBooking: "Agendamiento de Citas o Servicios",
      templateSupport: "Soporte y Derivación a Humano",
      filterAll: "Todos los flujos",
      filterActive: "Activos",
      filterDraft: "Borradores",
      exportFlow: "Exportar JSON",
      importFlow: "Importar Flujo"
    },
    edit: {
      title: "Editor de Flujo: {name}",
      save: "Guardar Cambios",
      publish: "Publicar Flujo"
    },
    logs: {
      title: "Ejecuciones del Flujo: {name}",
      subtitle: "Historial de contactos que han interactuado con este flujo",
      contact: "Contacto",
      startedAt: "Iniciado el",
      lastNode: "Último Bloque",
      status: "Estado",
      completed: "Completado",
      abandoned: "Incompleto / Abandonado",
      handoff: "Transferido a Agente",
      noLogs: "No hay ejecuciones registradas para este flujo.",
      viewSteps: "Ver pasos recorridos",
      close: "Cerrar",
      duration: "Duración",
      timeSeconds: "{sec} seg",
      timeMinutes: "{min} min",
      filterAll: "Todos",
      filterCompleted: "Completados",
      filterHandoff: "Transferidos"
    },
    builder: {
      addNode: "Agregar Bloque",
      nodeMessage: "Enviar Mensaje",
      nodeQuestion: "Preguntar y Esperar Respuesta",
      nodeButtons: "Botones de Opción",
      nodeCondition: "Condición Lógica (Si/No)",
      nodeSetTag: "Asignar Etiqueta",
      nodeAssignAgent: "Transferir a Agente Humano",
      nodeHttp: "Consulta API Externa",
      nodeAiReply: "Respuesta con Agente IA Gemini",
      nodeDelay: "Esperar Tiempo",
      nodeEnd: "Fin del Flujo",
      canvasHint: "Arrastra los conectores para enlazar los bloques de conversación",
      zoomIn: "Acercar (+)",
      zoomOut: "Alejar (-)",
      fitView: "Centrar Pantalla",
      testFlow: "Probar Flujo en Simulador",
      saveDraft: "Guardar Borrador",
      saving: "Guardando...",
      publishedSuccess: "¡Flujo publicado con éxito en WhatsApp!",
      nodeProperties: "Propiedades del Bloque",
      deleteNode: "Eliminar Bloque",
      startNodeTitle: "Inicio del Flujo",
      startKeywordLabel: "Palabras clave que activan este flujo (separadas por coma):",
      startKeywordPlaceholder: "hola, precio, catalogo, info, menu",
      messageTextLabel: "Texto del mensaje:",
      messagePlaceholder: "Escribe lo que el bot responderá...",
      buttonsLabel: "Opciones de botones (máximo 3 en WhatsApp):",
      addButton: "+ Agregar Botón"
    },
    validation: {
      errorTitle: "El flujo tiene errores de conexión",
      disconnectedNodes: "Hay bloques sin conectar en el diagrama.",
      missingStart: "El bloque de inicio no tiene mensaje o disparador configurado."
    },
    editorState: {
      unsavedChanges: "Tienes cambios sin guardar en el flujo.",
      discard: "Descartar",
      keepEditing: "Seguir editando",
      autoSaved: "Guardado automáticamente",
      errorSaving: "Error al guardar el flujo"
    },
    summary: {
      title: "Resumen del Flujo",
      totalBlocks: "Total de Bloques: {count}",
      totalKeywords: "Palabras Clave: {keywords}",
      statusActive: "Activo para todos los clientes entrantes",
      statusInactive: "Inactivo (No responderá hasta que lo publiques)",
      activateBtn: "Activar Flujo",
      deactivateBtn: "Pausar Flujo",
      lastModified: "Última edición: {date}",
      triggerType: "Tipo de Activador",
      triggerInbound: "Cualquier mensaje entrante",
      triggerKeyword: "Por coincidencia de palabra clave",
      triggerManual: "Activación manual desde el chat",
      runsMonth: "{count} ejecuciones este mes",
      completionRate: "{pct}% de tasa de finalización",
      avgDropoff: "Bloque con mayor abandono: {node}",
      copyShareLink: "Copiar enlace de prueba",
      linkCopied: "Enlace copiado al portapapeles"
    }
  },
  Settings: {
    pageTitle: "Configuración de la Cuenta",
    pageDesc: "Administra los parámetros de tu empresa, números de WhatsApp, miembros del equipo y agentes de IA",
    overview: {
      title: "Información General",
      description: "Datos principales de la empresa, moneda del sistema y resumen del plan contratado.",
      companyName: "Nombre de la Empresa",
      companyNamePlaceholder: "Ej: Inversiones Globales C.A.",
      saveCompany: "Guardar Nombre",
      saving: "Guardando...",
      saveSuccess: "Nombre de empresa actualizado con éxito.",
      saveFailed: "Error al actualizar nombre de empresa.",
      planCardTitle: "Plan SaaS Activo & Cuotas de Consumo",
      planCardDesc: "Límites por conversaciones de 24 horas y balance de recursos.",
      currentPlan: "Plan Actual",
      cycleRenews: "Renovación del Ciclo",
      cycleDaysLeft: "Quedan {days} días para la renovación",
      conversationsUsage: "Conversaciones de Hoy (Ventana 24h)",
      audiosUsage: "Notas de Voz Procesadas",
      ocrUsage: "Comprobantes Pago Móvil (OCR)",
      topUpAddon: "Recargar Conversaciones (+100 Conv por $5)"
    },
    members: {
      title: "Miembros del Equipo",
      description: "Gestiona los agentes y administradores con acceso a la bandeja de entrada y al CRM.",
      inviteMember: "Invitar Miembro",
      nameCol: "Nombre",
      emailCol: "Correo",
      roleCol: "Rol en la Empresa",
      joinedCol: "Fecha de Ingreso",
      actionsCol: "Acciones",
      roleOwner: "Propietario",
      roleAdmin: "Administrador",
      roleAgent: "Agente de Ventas / Atención",
      roleViewer: "Observador (Solo Lectura)",
      roleSupport: "Soporte / Operaciones",
      removeMember: "Remover Miembro",
      confirmRemove: "¿Estás seguro de remover a este miembro del equipo?",
      removedSuccess: "Miembro removido con éxito",
      loadFailed: "Error al cargar miembros del equipo",
      changeRole: "Cambiar Rol",
      roleUpdated: "Rol actualizado con éxito",
      maxAgentsReached: "Has alcanzado el límite máximo de agentes permitido por tu plan actual ({max}). Para agregar más miembros, mejora tu plan.",
      seatQuotaNotice: "Tu plan te permite {max} agente(s) en total. Tienes {current} activos.",
      emptyMembers: "No hay otros miembros registrados en esta cuenta.",
      searchPlaceholder: "Buscar miembro por nombre o correo...",
      leaveAccount: "Salir de la cuenta",
      transferOwnership: "Transferir Propiedad de la Empresa",
      transferNotice: "Esta acción transferirá la titularidad legal de la cuenta a otro administrador.",
      you: "(Tú)",
      invitedBadge: "Invitación Pendiente",
      resendInvite: "Reenviar Invitación",
      cancelInvite: "Cancelar Invitación"
    },
    invite: {
      title: "Invitar Nuevo Agente",
      desc: "Envía un enlace de invitación para que un miembro de tu equipo se registre en la empresa.",
      emailLabel: "Correo Electrónico del Invitado *",
      emailPlaceholder: "agente@tuempresa.com",
      roleLabel: "Rol a Asignar *",
      sendInvite: "Generar Enlace de Invitación",
      generating: "Generando invitación...",
      inviteLinkTitle: "Enlace de Invitación Generado",
      inviteLinkDesc: "Copia este enlace y envíaselo al miembro de tu equipo para que complete su registro:",
      copyLink: "Copiar Enlace",
      copied: "¡Enlace copiado al portapapeles!",
      done: "Listo",
      cancel: "Cancelar",
      limitError: "Tu plan actual no permite más agentes. Por favor mejora tu plan para invitar a más miembros.",
      invalidEmail: "Ingresa un correo electrónico válido",
      inviteSuccess: "Invitación generada con éxito",
      revokeInvite: "Revocar",
      revokedSuccess: "Invitación revocada",
      expiresIn: "Expira en 7 días",
      pendingInvitesTitle: "Invitaciones Pendientes ({count})",
      noPendingInvites: "No hay invitaciones pendientes.",
      roleDescAdmin: "Puede gestionar configuraciones, miembros, WhatsApp y todo el CRM.",
      roleDescAgent: "Puede responder chats, gestionar tratos y ver contactos.",
      roleDescViewer: "Solo puede ver la información, sin enviar mensajes ni modificar datos."
    },
    tagsAndFields: {
      title: "Etiquetas y Campos",
      description: "Organiza tus contactos y conversaciones mediante etiquetas y campos personalizados.",
      tagsTab: "Etiquetas de Contacto",
      fieldsTab: "Campos Personalizados",
      newTag: "Nueva Etiqueta",
      newField: "Nuevo Campo",
      tagName: "Nombre de la Etiqueta",
      tagColor: "Color de la Etiqueta",
      createTag: "Crear Etiqueta",
      tagCreated: "Etiqueta creada con éxito",
      tagDeleted: "Etiqueta eliminada",
      confirmDeleteTag: "¿Eliminar esta etiqueta? Se quitará de todos los contactos asociados.",
      emptyTags: "No has creado etiquetas todavía. Las etiquetas te permiten segmentar clientes fácilmente.",
      fieldName: "Nombre del Campo",
      fieldType: "Tipo de Campo",
      emptyFields: "No has configurado campos adicionales.",
      save: "Guardar",
      saving: "Guardando...",
      cancel: "Cancelar",
      delete: "Eliminar",
      tagsCount: "{count} contactos con esta etiqueta",
      usageExample: "Ejemplos: VIP, Interesado, Cliente Moroso, Distribuidor Mayorista"
    },
    templates: {
      title: "Plantillas de WhatsApp (Meta)",
      description: "Gestiona las plantillas oficiales aprobadas por WhatsApp para iniciar conversaciones fuera de la ventana de 24 horas.",
      newTemplate: "Nueva Plantilla",
      syncTemplates: "Sincronizar con WhatsApp",
      syncing: "Sincronizando...",
      syncSuccess: "Plantillas sincronizadas con éxito",
      statusApproved: "Aprobada por Meta",
      statusPending: "En Revisión por Meta",
      statusRejected: "Rechazada por Meta",
      nameCol: "Nombre de Plantilla",
      categoryCol: "Categoría",
      languageCol: "Idioma",
      statusCol: "Estado",
      actionsCol: "Acciones",
      categoryMarketing: "Marketing / Promocional",
      categoryUtility: "Utilidad / Notificaciones",
      categoryAuth: "Autenticación (OTP)",
      emptyTitle: "Sin plantillas registradas",
      emptyDesc: "Crea tu primera plantilla para enviar notificaciones masivas y mensajes fuera de la ventana de 24 horas.",
      createFirst: "Crear primera plantilla",
      templateNameLabel: "Nombre Técnico de la Plantilla *",
      templateNameHint: "Solo letras minúsculas, números y guiones bajos (Ej: bienvenida_clientes_nuevos)",
      categoryLabel: "Categoría de WhatsApp *",
      languageLabel: "Idioma de la Plantilla *",
      headerSection: "Encabezado (Opcional)",
      headerTypeText: "Texto Corto",
      headerTypeMedia: "Foto / Imagen Adjunta",
      headerTypeDoc: "Documento PDF",
      bodySection: "Cuerpo del Mensaje (Obligatorio) *",
      bodyPlaceholder: "Hola {{1}}, gracias por comunicarte con {{2}}. Tu pedido #{{3}} está listo para entrega.",
      bodyHint: "Usa variables numeradas como {{1}}, {{2}} para personalizar el contenido por cada cliente.",
      footerSection: "Pie de Página (Opcional)",
      footerPlaceholder: "Responde 'BAJA' para no recibir más promociones",
      buttonsSection: "Botones Interactivos (Opcional)",
      buttonTypeQuickReply: "Respuesta Rápida",
      buttonTypeUrl: "Enlace Web (URL)",
      buttonTypePhone: "Llamar por Teléfono",
      addButton: "+ Agregar Botón",
      buttonTextPlaceholder: "Texto del botón (Ej: Ver Catálogo)",
      submitToMeta: "Enviar a Meta para Aprobación",
      submitting: "Enviando a Meta...",
      submitSuccess: "Plantilla enviada a WhatsApp para su revisión.",
      previewTitle: "Vista Previa en WhatsApp",
      deleteTemplate: "Eliminar Plantilla",
      confirmDelete: "¿Seguro que deseas eliminar esta plantilla de WhatsApp?",
      deletedSuccess: "Plantilla eliminada",
      rejectReason: "Motivo de rechazo por Meta: {reason}"
    },
    roles: {
      owner: "Propietario de la Empresa",
      ownerDesc: "Acceso total e irrestricto, control de facturación, suscripción y eliminación de la cuenta.",
      admin: "Administrador",
      adminDesc: "Gestiona todas las configuraciones, conexión de WhatsApp, miembros y datos del CRM.",
      agent: "Agente Operativo",
      agentDesc: "Atiende chats en la bandeja de entrada, mueve tratos en el embudo y edita contactos.",
      viewer: "Observador",
      viewerDesc: "Acceso de solo lectura para auditorías y visualización de reportes.",
      support: "Soporte Técnico / Ventas",
      supportDesc: "Gestiona clientes, resuelve dudas operativas y da seguimiento comercial."
    },
    whatsapp: {
      title: "Conexión de WhatsApp (Evolution API / Meta)",
      description: "Conecta el número de WhatsApp de tu empresa mediante código QR para recibir y enviar mensajes automáticamente.",
      connectionStatus: "Estado de Conexión",
      statusConnected: "Conectado y En Línea",
      statusDisconnected: "Desconectado",
      statusConnecting: "Esperando escaneo de código QR...",
      phoneConnected: "Número Vinculado: {phone}",
      instanceName: "Instancia del Negocio: {instance}",
      scanQrTitle: "Escanea el Código QR con tu WhatsApp",
      scanQrInstructions: "1. Abre WhatsApp en tu teléfono.\n2. Ve a Menú (o Ajustes) > Dispositivos vinculados.\n3. Toca 'Vincular un dispositivo' y apunta la cámara a este código QR.",
      reloadQr: "Actualizar Código QR",
      disconnect: "Desconectar Número",
      confirmDisconnect: "¿Seguro que deseas desconectar este número de WhatsApp? Se pausará la recepción de mensajes.",
      disconnecting: "Desconectando...",
      disconnectedSuccess: "Número de WhatsApp desconectado.",
      connectedSuccess: "¡WhatsApp vinculado y listo para operar!",
      connectNewPhone: "Conectar Nuevo Número de WhatsApp",
      providerType: "Tipo de Conexión",
      providerEvolution: "Conexión Directa por QR (Evolution API) - Recomendada",
      providerMetaCloud: "API Oficial Meta Cloud API (Tokens / WABA)",
      testSendTitle: "Prueba de Envío",
      testSendDesc: "Envía un mensaje de prueba a tu número personal para verificar la conexión.",
      testPhoneLabel: "Tu Número Telefónico",
      testPhonePlaceholder: "+58 412 1234567",
      testMessageLabel: "Mensaje de Prueba",
      testMessageDefault: "¡Hola! Este es un mensaje de prueba enviado desde mi nuevo CRM de WhatsApp.",
      sendTest: "Enviar Mensaje de Prueba",
      sendingTest: "Enviando...",
      testSuccess: "¡Mensaje de prueba enviado exitosamente!",
      testFailed: "Error al enviar mensaje de prueba. Verifica que el número tenga WhatsApp activo.",
      webhookStatus: "Estado del Webhook de Eventos",
      webhookActive: "Recepción de Mensajes en Tiempo Real: Activa",
      webhookWarning: "Si experimentas retrasos, verifica que el webhook esté apuntando a crm.neuronix.com.ve"
    },
    sections: {
      general: "General & Plan",
      whatsapp: "WhatsApp (QR)",
      aiConfig: "Configuración de IA",
      aiKnowledge: "Base de Conocimientos",
      members: "Miembros del Equipo",
      templates: "Plantillas Meta",
      pipelines: "Etapas del Embudo",
      tags: "Etiquetas & Campos",
      apiKeys: "Claves API (REST)",
      appearance: "Apariencia",
      security: "Seguridad y Acceso"
    },
    groups: {
      workspace: "Configuración de Empresa",
      personal: "Ajustes Personales"
    },
    profile: {
      title: "Mi Perfil Personal",
      desc: "Actualiza tu nombre, correo y contraseña de acceso al sistema.",
      fullName: "Nombre Completo",
      email: "Correo Electrónico",
      avatar: "Foto de Perfil",
      saveProfile: "Guardar Cambios",
      saving: "Guardando...",
      saveSuccess: "Perfil actualizado exitosamente.",
      saveFailed: "Error al actualizar perfil.",
      changePasswordTitle: "Cambiar Contraseña",
      currentPassword: "Contraseña Actual",
      newPassword: "Nueva Contraseña",
      confirmPassword: "Confirmar Nueva Contraseña",
      updatePassword: "Cambiar Contraseña",
      updatingPassword: "Actualizando contraseña...",
      passwordChanged: "Contraseña actualizada con éxito.",
      passwordTooShort: "La contraseña debe tener al menos {min} caracteres",
      passwordMismatch: "Las contraseñas no coinciden",
      currentPasswordIncorrect: "La contraseña actual es incorrecta",
      passwordUpdateFailed: "Error al actualizar contraseña: {message}",
      sessionsTitle: "Sesiones Activas",
      sessionsDesc: "Cierra sesión en todos los dispositivos vinculados.",
      signOutAll: "Cerrar sesión en todos los dispositivos",
      signOutConfirmTitle: "¿Cerrar sesión en todas partes?",
      signOutConfirmDesc: "Tendrás que volver a iniciar sesión en todos tus dispositivos.",
      cancel: "Cancelar",
      signingOut: "Cerrando sesión...",
      signOutEverywhere: "Cerrar sesión en todo",
      signOutFailed: "Error al cerrar sesiones: {message}"
    },
    appearance: {
      title: "Apariencia y Tema",
      description: "Personaliza el modo oscuro, modo claro y el color de acento de la aplicación.",
      mode: "Modo de Visualización",
      useMode: "Usar modo {mode}",
      active: "Activo",
      accentColor: "Color de Acento",
      useTheme: "Usar tema {name}"
    },
    security: {
      title: "Seguridad y Accesos",
      description: "Gestiona tu contraseña, autenticación y sesiones activas."
    },
    apiKeys: {
      title: "Claves de API REST",
      description: "Permite integrar sistemas externos como Zapier, Make o tu propio backend con el CRM (/api/v1).",
      newApiKey: "Nueva Clave de API",
      noApiKeys: "No has generado claves de API aún.",
      createOneHint: "Haz clic en Nueva Clave de API para crear una.",
      askAdminHint: "Pide a un administrador que genere una clave.",
      revoked: "Revocada",
      expired: "Expirada",
      noScopes: "Sin permisos",
      created: "Creada el {date}",
      lastUsed: "Último uso: {date}",
      neverUsed: "Nunca utilizada",
      expires: "Expira el {date}",
      revoke: "Revocar Clave",
      revokeSuccess: "Clave \"{name}\" revocada con éxito",
      revokeFailed: "Error al revocar clave",
      loadFailed: "Error al cargar claves de API",
      createError: "Error al crear clave de API",
      nameRequired: "Asigna un nombre a la clave",
      nameLabel: "Nombre Descriptivo",
      namePlaceholder: "Ej: Integración con Tienda Online",
      scopesLabel: "Permisos de Acceso",
      scopesHint: "Una clave sin permisos solo podrá consultar información básica de verificación.",
      cancel: "Cancelar",
      creating: "Creando...",
      createKey: "Crear Clave de API",
      copyTitle: "Copia tu Clave de API",
      copyDesc: "Esta es la única vez que se mostrará la clave completa. Guárdala en un lugar seguro.",
      apiKeyLabel: "Clave de API Secreta",
      copy: "Copiar",
      copySuccess: "¡Clave de API copiada al portapapeles!",
      copyFailed: "Error al copiar — selecciona y copia manualmente",
      newKeyTitle: "Generar Clave de API",
      newKeyDesc: "Asigna solo los permisos necesarios para tu integración.",
      done: "Entendido",
      networkError: "No se pudo conectar con el servidor"
    },
    deals: {
      title: "Ventas y Moneda Predeterminada",
      description: "Moneda utilizada para el registro de tratos y los totales del panel de control.",
      defaultCurrency: "Moneda Principal de Operación",
      defaultCurrencyDesc: "Los nuevos tratos se crearán en esta moneda y los reportes consolidarán los montos en ella.",
      currencyLabel: "Código de Moneda (ISO)",
      adminOnlyHint: "Solo los administradores pueden cambiar la moneda del sistema.",
      save: "Guardar Moneda",
      saving: "Guardando...",
      saveFailed: "Error al guardar moneda",
      saveSuccess: "Moneda principal actualizada con éxito"
    },
    aiConfig: {
      title: "Configuración del Agente de Inteligencia Artificial",
      description: "Configura el motor de IA que responderá automáticamente por WhatsApp, transcribirá notas de voz y analizará captures de transferencias.",
      adminOnlyConfig: "Solo administradores y propietarios pueden modificar la configuración de IA.",
      loadFailed: "Error al cargar configuración de IA",
      providerAndKey: "Proveedor de IA & Clave Secreta",
      encryptionNotice: "Tu clave de API se almacena encriptada de forma segura (AES-256-GCM).",
      provider: "Proveedor de Inteligencia Artificial",
      model: "Modelo Seleccionado",
      apiKey: "Clave de API (API Key)",
      testKey: "Probar Conexión",
      testSuccess: "¡Conexión Exitosa! El proveedor respondió correctamente.",
      testRejected: "El proveedor rechazó la clave. Verifica que sea válida.",
      testNetworkError: "No se pudo conectar con el proveedor de IA.",
      embeddingsKey: "Clave para Búsqueda Semántica de Catálogos",
      optionalSemanticSearch: "(Opcional — permite búsqueda conceptual inteligente en catálogos)",
      embeddingsHint: "Clave de OpenAI para incrustar vectores semánticos (text-embedding-3-small){sameKeyText}. Si la dejas vacía, se usará búsqueda por palabras clave en los PDFs.",
      sameKeyText: " — puede ser la misma clave",
      behaviour: "Comportamiento del Agente & Prompt del Negocio",
      behaviourDesc: "Indica a la IA el rol de tu negocio, catálogo de productos, políticas, tono y qué responder ante pagos móviles o audios.",
      businessContext: "Instrucciones del Negocio (Prompt del Sistema)",
      promptPlaceholder: "Ej: Somos una tienda de repuestos automotrices en Caracas. Responde de forma cordial y concisa. Los precios están en USD o tasa oficial del BCV...",
      enableAssistant: "Habilitar Asistente de IA",
      enableAssistantDesc: "Interruptor maestro. Activa las funciones de IA y el botón 'Redactar con IA' en la bandeja de entrada.",
      autoReply: "Respuesta Automática a Mensajes Entrantes de WhatsApp",
      autoReplyDesc: "El bot responderá automáticamente los mensajes de clientes entrantes usando Gemini, tus notas de voz y tus catálogos.",
      maxAutoReplies: "Límite de Respuestas Automáticas Consecutivas",
      maxAutoRepliesDesc: "Tras este número de respuestas automáticas seguidas en un chat sin intervención de un humano, el bot pausa y espera.",
      handoffTo: "Derivar Conversación a",
      handoffToDesc: "Cuando el bot no pueda resolver o el cliente pida un humano, transferirá el chat aquí.",
      handoffQueue: "Cola General (Cualquier agente disponible puede tomarlo)",
      remove: "Eliminar Configuración",
      save: "Guardar Configuración de IA",
      missingModel: "Introduce el nombre del modelo.",
      missingApiKey: "Introduce tu API Key.",
      saveSuccess: "¡Configuración de IA guardada con éxito!",
      saveFailed: "Error al guardar la configuración de IA.",
      removeSuccess: "Configuración de IA eliminada.",
      removeFailed: "Error al eliminar configuración."
    },
    aiKnowledge: {
      loadFailed: "Error al cargar la base de conocimientos",
      openFailed: "Error al abrir documento",
      titleContentRequired: "El título y el contenido son obligatorios.",
      saveSuccessNew: "Documento agregado a la base de conocimientos.",
      saveSuccessUpdate: "Documento actualizado con éxito.",
      saveFailed: "Error al guardar documento.",
      removeSuccess: "Documento eliminado.",
      removeFailed: "Error al eliminar documento.",
      reindexSuccess: "Se reindexaron {count} documento(s) correctamente.",
      reindexFailed: "Error al reindexar.",
      title: "Base de Conocimientos del Agente (PDFs & Catálogos)",
      description: "Sube catálogos en PDF, listas de precios o preguntas frecuentes. El bot consultará esta información para responder exactamente lo que ofreces.{searchType}",
      semanticSearchOn: " Búsqueda semántica inteligente activa.",
      keywordSearchOn: " Búsqueda por palabras clave activa.",
      noDocs: "No hay documentos ni catálogos subidos aún.",
      editDocTitle: "Título del Documento",
      editDocTitlePlaceholder: "Ej: Catálogo de Servicios y Precios 2026",
      editDocContent: "Contenido / Texto",
      editDocContentPlaceholder: "Pega el texto, políticas o descripciones de productos...",
      cancel: "Cancelar",
      saveDoc: "Guardar Documento",
      addDoc: "Agregar Documento",
      reindex: "Reindexar Catálogos",
      reindexTooltip: "Vuelve a procesar todos los documentos para mejorar la búsqueda",
      loading: "Procesando..."
    }
  }
};

// Write out to messages/es.json
const outputPath = path.join(__dirname, '../messages/es.json');
fs.writeFileSync(outputPath, JSON.stringify(es, null, 2), 'utf8');
console.log('Successfully generated messages/es.json with', Object.keys(es).length, 'namespaces!');
